=== yethihahtwe/yethihahtwe.github.io/.astro/collections/workExperience.schema.json
{
  "$ref": "#/definitions/workExperience",
  "definitions": {
    "workExperience": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number"
        },
        "title": {
          "type": "string"
        },
        "company": {
          "type": "string"
        },
        "duration": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "title",
        "company",
        "duration",
        "description"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== yethihahtwe/yethihahtwe.github.io/src/content/work.json
[
  {
    "id": 7,
    "duration": "2012 - 2015",
    "company": "Health Updates Journal",
    "title": "Editor-in-chief",
    "description": "Content writing, translation of medical articles, social media page administration, hot line medical consultation, news reporting and interviewing medical persons."
  },
  {
    "id": 6,
    "duration": "2012 - 2021",
    "company": "Private Practice",
    "title": "General Practitioner/ Primary Care Physician",
    "description": "Private clinic providing primary healthcare, minor surgeries, and laboratory services. Collaborated with Population Services International and Myanmar Medical Association for TB and Malaria treatment programs. Founded and led `Heartyfarm` social welfare group organizing charity clinic activities."
  },
  {
    "id": 5,
    "duration": "April 2022 - Dec 2022",
    "company": "Ethnic Health System Strengthening Group",
    "title": "ICT Consultant",
    "description": "Comprehensive learning material creation and development of a Learning Management System (LMS)."
  },
  {
    "id": 4,
    "duration": "Dec 2022 - Sept 2024",
    "company": "Ethnic Health System Strengthening Group",
    "title": "ICT Manager",
    "description": "Led data-driven application development and visualization dashboards. Supervise and manage day-to-day organizational IT tasks and systems."
  },
  {
    "id": 3,
    "duration": "Nov 2024 - Jan 2025",
    "company": "Civil Health and Development Network",
    "title": "Mobile and Web application development contractor",
    "description": "Development and implementation of a comprehensive malaria case reporting system. An offlie-first mobile app and a web based information management system."
  },
  {
    "id": 2,
    "duration": "Nov 2024 - Feb 2025",
    "company": "Suwannimit Foundation",
    "title": "IT Policy & Cybersecurity Consultant",
    "description": "A contractor role in providing cybersecurity training and developing IT policies related to data storage security and record management."
  },
  {
    "id": 1,
    "duration": "Nov 2024 - present",
    "company": "Ethnic Health System Strengthening Group",
    "title": "IT Specialist",
    "description": "A technical specialist role in developing information management systems."
  }
]
